---
- name: Configure MongoDB
  hosts: db
  become: true
  roles:
  - db
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod
  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted

